### ISSUE TITLE
Global 'return' in browser.js

### ISSUE THREAD

**Issue by PavelHasala** [unshiftio/readystate#6]
When trying to build my app using webpack, it fails because of global return. I gues it would be nice, to not have to tweak building process, because of module taking advantage of something non-standart
```
ERROR in ../~/readystate/browser.js
Module parse failed: /Users/hakim/Sites/DOODLINGS/tooltip-info-bubble/node_modules/readystate/browser.js 'return' outside of function (15:2)
You may need an appropriate loader to handle this file type.

| //
| if (complete === doc.readyState) {
|   return readystate.change(complete);
| }
```

**Comment by 3rd-Eden** [comment]
Right. The reason it's there because I assume that browserify processes wrap the contents in a function. So the return would work. I'll wrap it in a massive self-executing thing.

**Comment by 3rd-Eden** [comment]
Publish 0.2.0 with a fix.

**Comment by PavelHasala** [comment]
Works like a charm, thanks.
