### ISSUE TITLE
How to unlisten?

### ISSUE THREAD

**Issue by binarykitchen** [unshiftio/readystate#8]
Is there a function to remove the event?

**Comment by 3rd-Eden** [comment]
There isn't any, sorry. But feel free to add that in form of PR.

**Comment by binarykitchen** [comment]
@3rd-Eden alright - where would you start in the code?

**Comment by 3rd-Eden** [comment]
From the code we can see that the events are stored in an object where the value's will be an array of object with fn and context references: https://github.com/unshiftio/readystate/blob/master/readystate.js#L23-L24

So all you would need to do is check if the event is in `_events` and then iterate over the array and compare the `object.fn` with the supplied function and splice it out of the array.

**Comment by binarykitchen** [comment]
here you go @3rd-Eden

**Comment by 3rd-Eden** [comment]
Awesome, published it as 0.3.0

**Comment by binarykitchen** [comment]
hmmm just had a try with the new version i am not sure if this is really working properly @3rd-Eden 

after calling `removeAllListeners()` in my app, somehow the `readystate.interactive` hook was still run afterwards. i expect it not to be run anymore ever again after calling removeAllListeners.

did i miss something in the PR?
